Repository scipy/scipy-articles, pull requests merged in 2019-07, with the labels that each got.

#144 MAINT: add benchmark supporting data
  scipy-1.0/supporting_info/asv_bench/cKDTree/asv.conf.json.cython018
  scipy-1.0/supporting_info/asv_bench/cKDTree/asv.conf.json.cython0273
  scipy-1.0/supporting_info/asv_bench/cKDTree/benchmark_patch_diff.txt
  scipy-1.0/supporting_info/asv_bench/cKDTree/benchmarks.json.cython018
  scipy-1.0/supporting_info/asv_bench/cKDTree/ckdtree_asv_supporting.tar.xz
Labels: maintenance

#158 Add subsection on documentation.
  scipy-1.0/paper.tex
  scipy-1.0/references.bib
Labels: content

#177 Updated author list and contribution statement, added consortium
  scipy-1.0/consortium.tex
  scipy-1.0/core-dev.tex
  scipy-1.0/paper.tex
Labels: authors

#193 MAINT: adjust covlett for Nature Methods
  scipy-1.0/covlett.tex
Labels: maintenance
